superkingdom_5mers: ""
superkingdom_6mers: ""
superkingdom_7mers: ""

kingdom_5mers: ""
kingdom_6mers: ""
kingdom_7mers: ""

phylum_5mers: ""
phylum_6mers: ""
phylum_7mers: ""

plots_dir: ""
processed_files_dir: ""
7mers_to_proteome_file: ""
proteome_to_superkingdom_file: ""

peptide_match_dir: ""
multi_species_goea_files_dir: ""
goa_db_parquet_file: ""
taxid_mappings_parquet: ""
obo_file: ""

protein_entry_files_dir: ""
protein_entry_output_dir: ""
interpro_db_parquet: ""

structural_analysis_dir: ""

alphamissense_data_dir: ""

substitution_analysis_dir: ""
substitution_analysis_peptide_match_results: ""
substitution_analysis_id_mapping: ""
ranked_lineage_file: ""
merged_dmp_file: ""