# -------------------------------------------------------------------
# Configuration File for Taxonomic Quasi-Primes Project
#
# Instructions for Reproducibility:
# 1. Modify `base_dir` to the absolute path on your system where the
#    project's main data directories are stored.
# 2. The other paths are relative to `base_dir`. Do not change them
#    unless you have intentionally altered the data directory structure.
# -------------------------------------------------------------------

paths:
  # Base directory for relative paths
  base_dir: ''

  # Input directories
  inputs:
    # This path is absolute in your script, so we'll treat it as such.
    mapping_files: ''
    # This path was constructed relative to base_dir
    quasi_prime_extractions: ''

  # Output directories (these will be created relative to base_dir)
  outputs:
    plots: 'plots'
    peptides_over_90: 'qp_peptides_over_90_per_phylum'


    